//
//  StyleKitName.m
//  GrumpyGif
//
//  Created by Armando Carmona on 07/03/15.
//  Copyright (c) 2015 AEC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "GrumpyGifStyleKit.h"


@implementation GrumpyGifStyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawSearchWithFrame: (CGRect)frame
{
    //// Color Declarations
    UIColor* color3 = [UIColor colorWithRed: 0.319 green: 0.722 blue: 0.655 alpha: 1];
    UIColor* color0 = [UIColor colorWithRed: 0.556 green: 0.372 blue: 0.168 alpha: 1];
    UIColor* color2 = [UIColor colorWithRed: 0.788 green: 0.566 blue: 0.305 alpha: 1];
    UIColor* color5 = [UIColor colorWithRed: 0.902 green: 0.912 blue: 0.921 alpha: 1];
    UIColor* color6 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 0.7];
    
    //// Shape Drawing
    UIBezierPath* shapePath = UIBezierPath.bezierPath;
    [shapePath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.08363 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98137 * CGRectGetHeight(frame))];
    [shapePath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.01863 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98137 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.06569 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.99931 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.03656 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.99931 * CGRectGetHeight(frame))];
    [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.01863 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98137 * CGRectGetHeight(frame))];
    [shapePath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.01863 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.91635 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.00066 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.96340 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.00066 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93431 * CGRectGetHeight(frame))];
    [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.35509 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57988 * CGRectGetHeight(frame))];
    [shapePath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.42009 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57992 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.37301 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56198 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.40212 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56198 * CGRectGetHeight(frame))];
    [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.42009 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57992 * CGRectGetHeight(frame))];
    [shapePath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.42007 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64490 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.43804 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59783 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.43804 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62692 * CGRectGetHeight(frame))];
    [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.08363 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98137 * CGRectGetHeight(frame))];
    [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.08363 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98137 * CGRectGetHeight(frame))];
    [shapePath closePath];
    shapePath.miterLimit = 4;
    
    shapePath.usesEvenOddFillRule = YES;
    
    [color0 setFill];
    [shapePath fill];
    
    
    //// Shape 2 Drawing
    UIBezierPath* shape2Path = UIBezierPath.bezierPath;
    [shape2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.12858 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.99370 * CGRectGetHeight(frame))];
    [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.03901 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.96101 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.11286 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 1.00939 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.07276 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.99478 * CGRectGetHeight(frame))];
    [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.03901 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.96101 * CGRectGetHeight(frame))];
    [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.00631 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87144 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.00522 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92723 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + -0.00939 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88712 * CGRectGetHeight(frame))];
    [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.36363 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51407 * CGRectGetHeight(frame))];
    [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.45323 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54679 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.37936 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49839 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.41946 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51302 * CGRectGetHeight(frame))];
    [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.45323 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54679 * CGRectGetHeight(frame))];
    [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.48591 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63639 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.48700 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58050 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.50166 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62061 * CGRectGetHeight(frame))];
    [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.12858 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.99370 * CGRectGetHeight(frame))];
    [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.12858 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.99370 * CGRectGetHeight(frame))];
    [shape2Path closePath];
    shape2Path.miterLimit = 4;
    
    shape2Path.usesEvenOddFillRule = YES;
    
    [color2 setFill];
    [shape2Path fill];
    
    
    //// Shape 3 Drawing
    UIBezierPath* shape3Path = UIBezierPath.bezierPath;
    [shape3Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63753 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69292 * CGRectGetHeight(frame))];
    [shape3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.30707 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36245 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.45505 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69292 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.30707 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54497 * CGRectGetHeight(frame))];
    [shape3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63753 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03199 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.30707 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17992 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.45505 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03199 * CGRectGetHeight(frame))];
    [shape3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.96800 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36245 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.82009 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03199 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.96800 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17993 * CGRectGetHeight(frame))];
    [shape3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63753 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69292 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.96801 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54497 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.82009 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69292 * CGRectGetHeight(frame))];
    [shape3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63753 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69292 * CGRectGetHeight(frame))];
    [shape3Path closePath];
    shape3Path.miterLimit = 4;
    
    shape3Path.usesEvenOddFillRule = YES;
    
    [color3 setFill];
    [shape3Path fill];
    
    
    //// Shape 4 Drawing
    UIBezierPath* shape4Path = UIBezierPath.bezierPath;
    [shape4Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.34709 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52901 * CGRectGetHeight(frame))];
    [shape4Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.30009 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57598 * CGRectGetHeight(frame))];
    [shape4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.43533 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68535 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.30009 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57598 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.34301 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67079 * CGRectGetHeight(frame))];
    [shape4Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.46942 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65127 * CGRectGetHeight(frame))];
    [shape4Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.46942 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60720 * CGRectGetHeight(frame))];
    [shape4Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.34709 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52901 * CGRectGetHeight(frame))];
    [shape4Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.34709 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52901 * CGRectGetHeight(frame))];
    [shape4Path closePath];
    shape4Path.miterLimit = 4;
    
    shape4Path.usesEvenOddFillRule = YES;
    
    [color0 setFill];
    [shape4Path fill];
    
    
    //// Shape 5 Drawing
    UIBezierPath* shape5Path = UIBezierPath.bezierPath;
    [shape5Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38138 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10627 * CGRectGetHeight(frame))];
    [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38138 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61863 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.23986 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24775 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.23986 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47717 * CGRectGetHeight(frame))];
    [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.89375 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61866 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52290 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76014 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.75226 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76014 * CGRectGetHeight(frame))];
    [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.89375 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10627 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 1.03524 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47717 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 1.03524 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24775 * CGRectGetHeight(frame))];
    [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38138 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10627 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.75226 * CGRectGetWidth(frame), CGRectGetMinY(frame) + -0.03524 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.52289 * CGRectGetWidth(frame), CGRectGetMinY(frame) + -0.03524 * CGRectGetHeight(frame))];
    [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38138 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10627 * CGRectGetHeight(frame))];
    [shape5Path closePath];
    [shape5Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.82917 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55407 * CGRectGetHeight(frame))];
    [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.44596 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55407 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.72338 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65988 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.55180 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65990 * CGRectGetHeight(frame))];
    [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.44596 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17087 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.34013 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44827 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.34013 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27665 * CGRectGetHeight(frame))];
    [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.82917 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17084 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.55180 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06503 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.72338 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06503 * CGRectGetHeight(frame))];
    [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.82917 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55407 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.93503 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27668 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.93498 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44826 * CGRectGetHeight(frame))];
    [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.82917 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55407 * CGRectGetHeight(frame))];
    [shape5Path closePath];
    shape5Path.miterLimit = 4;
    
    shape5Path.usesEvenOddFillRule = YES;
    
    [color5 setFill];
    [shape5Path fill];
    
    
    //// Shape 6 Drawing
    UIBezierPath* shape6Path = UIBezierPath.bezierPath;
    [shape6Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.45824 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32701 * CGRectGetHeight(frame))];
    [shape6Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.47269 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36620 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.45147 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34179 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.45790 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35940 * CGRectGetHeight(frame))];
    [shape6Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.51193 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35180 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.48752 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37311 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.50513 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36652 * CGRectGetHeight(frame))];
    [shape6Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.51366 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34852 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.51193 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35180 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.51222 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35112 * CGRectGetHeight(frame))];
    [shape6Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.67775 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24040 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52390 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32976 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.57329 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.25012 * CGRectGetHeight(frame))];
    [shape6Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.70348 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21852 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.69041 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.23916 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.70039 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.23016 * CGRectGetHeight(frame))];
    [shape6Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.70432 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.20813 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.70432 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21525 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.70467 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21176 * CGRectGetHeight(frame))];
    [shape6Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.67205 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.18157 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.70269 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19190 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.68829 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17994 * CGRectGetHeight(frame))];
    [shape6Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.45824 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32701 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.51808 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19742 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.45975 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32402 * CGRectGetHeight(frame))];
    [shape6Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.45824 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32701 * CGRectGetHeight(frame))];
    [shape6Path closePath];
    shape6Path.miterLimit = 4;
    
    shape6Path.usesEvenOddFillRule = YES;
    
    [color6 setFill];
    [shape6Path fill];
}

#pragma mark Generated Images

+ (UIImage*)imageOfSearchWithFrame: (CGRect)frame
{
    UIGraphicsBeginImageContextWithOptions(frame.size, NO, 0.0f);
    [GrumpyGifStyleKit drawSearchWithFrame: frame];
    
    UIImage* imageOfSearch = [UIGraphicsGetImageFromCurrentImageContext() imageWithRenderingMode: UIImageRenderingModeAlwaysOriginal];
    UIGraphicsEndImageContext();
    
    return imageOfSearch;
}


@end
