//
//  StyleKitName.h
//  GrumpyGif
//
//  Created by Armando Carmona on 07/03/15.
//  Copyright (c) 2015 AEC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface GrumpyGifStyleKit : NSObject
+ (UIImage*)imageOfSearchWithFrame: (CGRect)frame;
@end
