//
//  GrumpyGifStyleKit.h
//  GrumpyGif
//
//  Created by Armando Carmona on 13/03/15.
//  Copyright (c) 2015 AEC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface GrumpyGifStyleKit : NSObject

// Generated Images
+ (UIImage*)imageOfSearchWithFrame: (CGRect)frame;
+ (UIImage*)imageOfShareWithFrame: (CGRect)frame;
+ (UIImage*)imageOfEliminateWithFrame: (CGRect)frame;

@end
